### ISSUE TITLE
Message not received ?

### ISSUE THREAD

**Issue by iliesaya** [RIAPS/riaps-core#55]
Hi, 
I have riaps installed on my arm64 nvidia jetson. The installation process was tricky, I may have forgotten something or compiled something wrong, but now I can launch riaps_deplo without error. 

I am trying to run the toy example WeatherMonitor, with the jetson as the Sensor and my dev VM as the monitor :

here is the bash output on the riaps_deplo from jetson (sensor)
```

`riaps@bbb-a9a0:~$ sudo -E riaps_deplo
ERROR:14:54:27,295:[7688]:root:Generic netlink protocol VFS_DQUOT not found
ERROR:14:54:27,297:[7688]:root:Please check if the protocol module is loaded
ERROR:14:54:27,298:[7688]:riaps.deplo.spcmon:SpcMonitorThread failure
RTNETLINK answers: No such file or directory
Ethernet link detected
Adding user `weathermonitora9a0' ...
Adding new group `weathermonitora9a0' (1001) ...
Adding new user `weathermonitora9a0' (1001) with group `weathermonitora9a0' ...
Not creating home directory `/home/weathermonitora9a0'.
Adding new user `weathermonitora9a0' to extra groups ...
Adding user `weathermonitora9a0' to group `audio' ...
Adding user `weathermonitora9a0' to group `video' ...
Adding user `weathermonitora9a0' to group `gdm' ...
[info]:14:56:09,265:[8171]:SENSOR:(PID 8171)-starting TempSensor, Sat Jun 22 14:56:09 2019
[info]:14:56:09,265:[8171]:SENSOR:Initial temp:65, Sat Jun 22 14:56:09 2019
[info]:14:56:14,660:[8171]:SENSOR:on_clock(): Temperature - 66, PID 8171, Sat Jun 22 14:56:14 2019
[info]:14:56:19,661:[8171]:SENSOR:on_clock(): Temperature - 67, PID 8171, Sat Jun 22 14:56:19 2019

`
```

and here is the output from riaps_deplo on the VM (monitor)
```
`riaps@riaps-devbox:~$ sudo -E riaps_deplo
RTNETLINK answers: No such file or directory
Ethernet link detected
[2019-06-22 06:55:37.644] [discovery] [info] Starting RIAPS DISCOVERY SERVICE 
[2019-06-22 06:55:37.645] [discovery] [info] Security is turned off
[2019-06-22 06:55:37.651] [discovery] [info] Starting DHT node on 192.168.1.106:4222 (000c2903984c)
[2019-06-22 06:55:37.653] [discovery] [info] DHT thread is initialized, starts beaconing.
Adding user `weathermonitor984c' ...
Adding new group `weathermonitor984c' (1000) ...
Adding new user `weathermonitor984c' (1000) with group `weathermonitor984c' ...
Not creating home directory `/home/weathermonitor984c'.
[info]:06:56:05,889:[2034]:MONITOR:(PID 2034)-starting TempMonitor, Sat Jun 22 06:56:05 2019
[2019-06-22 06:56:05.891] [discovery] [info] Register actor with PID - 2034 : /WeatherMonitor/WeatherReceiver/
[2019-06-22 06:56:07.071] [discovery] [info] Lookup: /WeatherMonitor/TempData/pub
`

```

Sensor seems to send without error its message, but monitor doesn't receive them. 
What could possibly be the issue ? disabling security didn't help.

thanks for your help. 

PS: Using a bbb instead of the jetson is working and the VM correctly receive the message, so it's something wrong with my jetson installation.

**Comment by MMetelko** [comment]
Make sure that the jetson RIAPS configuration file has security off.  I do not see the "Security is turned off" message in the jetson's riaps_deplo output.  

Also, there is an error related to VFS_DQUOT.  There was a manual step for quota that might not have been done yet.  See step 5 of ["To Build a RIAPS Virtual Machine Environment from Scratch"](https://github.com/RIAPS/riaps-integration/blob/master/riaps-x86runtime/vm-creation-readme.md).

**Comment by iliesaya** [comment]
Thank you for your answer @MMetelko  , yes I am sure that in /etc/riaps.conf the line Security is Off . same in the VM , in fact if the VM has security ON , riaps_ctrl doesn't see the jetson at all. So first both VM and jetson had security at ON , messages are sent but not received, then I changed security to OFF on both, rebooted, but nothing changed. 

Yes I didn,t managed to install the Quota , but I don't see how this could affect message not being sent. I digged up in the code and it looks like it just a thread monitoring used space without interfering. 

Could it be the timesync service that will block message if clock are not synchronized ?

**Comment by MMetelko** [comment]
You are correct in that Quota is not necessary at this point of getting this app to run, since it does not use resource management.  Timesync service is not involved in message connection process, so that should not have any impact.

It seems that the discovery process is not connecting completely.  We default to a C++ version of discovery working with OpenDHT.  There is also a redis version available that is Python based.  To isolate this further, try moving to the redis discovery and see if it works.  Currently the /usr/local/bin/riaps_disco is a soft link to /opt/riaps/amd64/bin/rdiscoveryd (keep in mind this link is architecture specific).  If you look in /usr/local/bin folder there is also a riaps_disco_redis.  Change the riaps_disco soft link on both systems to point to the riaps_disco_redis.  If this works, we can then narrow down the issue.

**Comment by iliesaya** [comment]
Here is what happen when riaps_disco_redis is used :

```
riaps@bbb-a9a0:/usr/local/bin$ sudo -E riaps_deplo
ERROR:11:18:21,475:[8643]:root:Generic netlink protocol VFS_DQUOT not found
ERROR:11:18:21,478:[8643]:root:Please check if the protocol module is loaded
ERROR:11:18:21,478:[8643]:riaps.deplo.spcmon:SpcMonitorThread failure
Ethernet link detected
Traceback (most recent call last):
  File "/usr/local/bin/riaps_disco", line 16, in <module>
    riaps.discd.main.main()
  File "/usr/local/lib/python3.6/dist-packages/riaps/discd/main.py", line 50, in main
    theDisco.start()
  File "/usr/local/lib/python3.6/dist-packages/riaps/discd/discs.py", line 53, in start
    self.server.bind(endpoint)
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use
```

**Comment by MMetelko** [comment]
To just use the python discovery for now, you can turn off and disable the systemd service for riaps-deplo.service on the jetson.  This service is setup to restart when stopped.  

```
sudo systemctl stop riaps-deplo.service
sudo systemctl disable riaps-deplo.service
```

riaps-externals compiles libraries like czmq and zyre, and then packages them into the /opt/riaps/armhf directories.  For your system, you should modify and run the [cmake](https://github.com/RIAPS/riaps-externals/blob/master/CMakeLists.txt) for your architecture.  Then you can add run the [DEBIAN postinst portion](https://github.com/RIAPS/riaps-externals/blob/master/DEBIAN/armhf/postinst) manually.  This portion is looking for binding files that were placed by in the cmake process in the /opt/riaps/armhf folder.  

```
rm -rf /tmp/pyzmq
git clone https://github.com/zeromq/pyzmq.git /tmp/pyzmq
cd tmp/pyzmq
git checkout tags/v17.1.2
python3 setup.py install

CFLAGS=-I/opt/riaps/armhf/include LDFLAGS=-L/opt/riaps/armhf/lib PATH=$PATH:/opt/riaps/armhf/bin pip3 install 'pycapnp==0.6.3'

CFLAGS=-I/opt/riaps/armhf/include LDFLAGS=-L/opt/riaps/armhf/lib PATH=$PATH:/opt/riaps/armhf/bin pip3 install /opt/riaps/armhf/bindings/czmq/python/ --verbose
CFLAGS=-I/opt/riaps/armhf/include LDFLAGS=-L/opt/riaps/armhf/lib PATH=$PATH:/opt/riaps/armhf/bin pip3 install /opt/riaps/armhf/bindings/zyre/python/ --verbose

rm -rf /tmp/pyzmq
```

I left out the basic pip packages listed in the Debian postinst since you already installed them and they are not involved int he czmq and zyre setup.
